import { LinearGradient } from 'expo-linear-gradient';
import { Mail, Pencil, Phone } from 'lucide-react-native';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Avatar } from '@/components/profile/Avatar';
import { Badge } from '@/components/profile/Badge';
import { Fonts, Radius, Spacing, brandColors, profileColors } from '@/constants/theme';
import type { PatientProfile } from '@/types/profile';
type ProfileHeaderProps = { profile: PatientProfile; onEdit: () => void };
export function ProfileHeader({ profile, onEdit }: ProfileHeaderProps) { return <LinearGradient colors={[profileColors.tint, profileColors.sky, brandColors.white]} style={styles.card}><Avatar name={profile.fullName} imageUrl={profile.avatarUrl} /><View style={styles.identity}><Text style={styles.name}>{profile.fullName}</Text><Badge /></View><View style={styles.contact}><View style={styles.contactRow}><Mail color={brandColors.primaryMuted} size={15}/><Text style={styles.contactText}>{profile.email || 'Email not added'}</Text></View><View style={styles.contactRow}><Phone color={brandColors.primaryMuted} size={15}/><Text style={styles.contactText}>{profile.phone || 'Phone not added'}</Text></View></View><Pressable onPress={onEdit} style={({ pressed }) => [styles.button, pressed && styles.buttonPressed]}><Pencil color={brandColors.white} size={16}/><Text style={styles.buttonText}>Edit profile</Text></Pressable></LinearGradient>; }
const styles = StyleSheet.create({ card: { alignItems: 'center', borderRadius: Radius.large, gap: Spacing.three, overflow: 'hidden', padding: Spacing.four }, identity: { alignItems: 'center', gap: Spacing.one }, name: { color: brandColors.primaryDark, fontFamily: Fonts.rounded, fontSize: 27, fontWeight: '800' }, contact: { alignItems: 'center', gap: Spacing.one }, contactRow: { alignItems: 'center', flexDirection: 'row', gap: Spacing.one }, contactText: { color: brandColors.slate, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '500' }, button: { alignItems: 'center', backgroundColor: brandColors.primary, borderRadius: Radius.pill, flexDirection: 'row', gap: Spacing.one, justifyContent: 'center', minHeight: 44, paddingHorizontal: Spacing.three }, buttonPressed: { backgroundColor: brandColors.primaryMuted }, buttonText: { color: brandColors.white, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '800' } });
