export const ENDPOINTS = {
  LOGIN: '/v1/accounts/auth/login/',
  REGISTER_PATIENT: '/v1/accounts/patients/register',
  REFRESH_TOKEN: '/v1/accounts/auth/refresh/',
  ME: '/v1/accounts/me/',
  PATIENT_PROFILE: '/v1/accounts/me/patient-profile/',
  USER_CONTEXTS: '/v1/accounts/me/contexts/',
  HOME_METADATA: '/v1/metadata/home/',
  HOME_FEED: '/v1/metadata/me/feed/',
  METADATA_CATEGORIES: '/v1/metadata/categories/',
  METADATA_CATEGORY: (slug: string) => `/v1/metadata/category/${encodeURIComponent(slug)}/`,
  METADATA_SEARCH: '/v1/metadata/search/',
  METADATA_FACETS: '/v1/metadata/facets/',
  DEVICES: '/v1/accounts/auth/devices/',
  CONSENTS: '/v1/clinics/clinic/patient/consents/',
  APPROVE_CONSENT: '/v1/clinics/clinic/patient/consents/approve/',
  REJECT_CONSENT: '/v1/clinics/clinic/patient/consents/reject/',
  MEMBERSHIPS: '/v1/clinics/clinic/patient/memberships/',
  PATIENT_CHART: '/v1/clinics/clinic/patient/chart/',
  DIAGNOSTICS: '/v1/clinics/clinic/patient/diagnostics/',
  UPCOMING_APPOINTMENTS: '/v1/appointments/me',
  PRESCRIPTIONS: '/v1/my/prescriptions/',
} as const;
